<?xml version="1.0"?>
<VaisResource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.geaviation.com/vais/config">
  <ResourceVersionInfo SchemaVersion="2" FileVersion="27" VaisToolName="ConfigEditor.exe" VaisToolVersion="3.0.0.0" />
  <ComputingResource ComputingResourceName="I-SIVB-PC-CommonSimulationRuntime" Description="I-SIVB PC , Connect with ReflectMemory net work and VIAS network" MachineName="I-SIVB_PC" CpuModel="WIN7/64">
    <ResourceUtilityAllocation UtilityName="I-SIVB RMC" />
  </ComputingResource>
</VaisResource>